# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f2d0e1e506906e5d71b672ab0d92682"
name = "Technoxify - MCP Assistance"
handle = "technoxify-mcp-assistance"
application_url = "https://rebate-baths-hydraulic-trees.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://rebate-baths-hydraulic-trees.trycloudflare.com/auth/callback",
  "https://rebate-baths-hydraulic-trees.trycloudflare.com/auth/shopify/callback",
  "https://rebate-baths-hydraulic-trees.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
